### ISSUE TITLE
Error 0x80004005

### ISSUE THREAD

**Issue by lazna** [gerardog/gsudo#102]
Windows 10 64 bit 10.0.19043.1110

C:\>gsudo defrag c:
```
Error: System.ComponentModel.Win32Exception (0x80004005): The operation was canceled by the user
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at gsudo.Helpers.ProcessFactory.StartElevatedDetached(String filename, String arguments, Boolean hidden)
   at gsudo.Commands.RunCommand.<Execute>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at gsudo.Program.<Start>d__1.MoveNext()
```

**Comment by gerardog** [comment]
Works for me:
```
C:\>gsudo defrag c:

Invoking defragmentation on (C:)...
```
`The operation was canceled by the user` indicates you did not accept the UAC popup.

**Comment by lazna** [comment]
You are righet, probably accidentally misclick to NO. Closing
